Update translate

diff --git a/.local/bin/translate b/.local/bin/translate
--- a/.local/bin/translate
+++ b/.local/bin/translate
@@ -106,11 +106,11 @@ primary="$(get_selection)"
 clip_menu="$(clip_menu "$primary" "$clipboard")"
 
 # Enter text
-text="$(printf '%s' $clip_menu | eval $DMENU_TEXT $@)" || exit 0
-text="$(get_text $text $clip_menu)"
+text="$(printf '%s' "$clip_menu" | eval "$DMENU_TEXT" '$@')" || exit 0
+text="$(get_text "$text" "$clip_menu")"
 
 # Choose target language
-target="$(lang_menu | eval $DMENU_LANG $@)" || exit 0
+target="$(lang_menu | eval "$DMENU_LANG" '$@')" || exit 0
 
 # If Define chosen, define term and exit
 [ "$target" = '[Define]' ] && {
@@ -130,6 +130,6 @@ case "$(choose_next "$translation" "$@")" in
 	*)                     exit 0 ;;
 esac
 
-echo "$output" | eval "$CLIP_COPY" || err 'Failed to copy! Is CLIP_COPY setting set properly?'
+echo "$output" | eval "$CLIP_COPY" || err 'Failed to copy. Is CLIP_COPY setting set properly?'
 
-notify-send 'transmenu' 'Translation copied to clipboard!'
+notify-send 'Translation copied to clipboard.'
